# Generated by Django 5.2.7 on 2025-11-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_actividad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='descripcion',
            new_name='detalle',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='wallet',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='confirmed_round',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('failed', 'Fallida')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='receiver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='sender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='txid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('admin_docente', 'Admin → Docente'), ('docente_alumno', 'Docente → Alumno')], max_length=30, null=True),
        ),
    ]
