"""
Django settings for algoweb project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^$e*$$=_u1wahfu0+47e)dc-_e5#87&w@nol17($@(o&n+-nee'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'wallet',  # Tu aplicación
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'algoweb.urls'


# === Configuración de Templates ===
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 👉 Importante: agrega la carpeta templates global dentro de la app "wallet"
        'DIRS': [BASE_DIR / 'wallet' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'algoweb.wsgi.application'


# === Base de datos ===
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# === Validación de contraseñas ===
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# === Internacionalización ===
LANGUAGE_CODE = 'es-mx'  # Español (México)
TIME_ZONE = 'America/Mexico_City'
USE_I18N = True
USE_TZ = True


# === Archivos estáticos (CSS, JS, imágenes) ===
STATIC_URL = '/static/'

# 👉 Permite que Django encuentre archivos estáticos dentro de tu app "wallet"
STATICFILES_DIRS = [
    BASE_DIR / 'wallet' / 'static'
]

# Carpeta donde se almacenarán archivos estáticos recopilados en producción
STATIC_ROOT = BASE_DIR / 'staticfiles'


# === Modelo de usuario personalizado ===
AUTH_USER_MODEL = 'wallet.User'


# === Clave primaria por defecto ===
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

